version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./dump.rdb
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 5000 -b '0.0.0.0'"
    volumes:
      - .:/shop_tight
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres